Algoritmo "exercico imc"
// Lógica de Programação 
// Professor : marcos monteiro 
 VAR
 nome :caractere
 peso,altura,imc:real
 inicio
 escreva ("digite  o nome.")
 leia(nome)
 escreva ("digite  a altura.")
 leia(altura)
 escreva ("digite  o peso.")
 leia(peso)
 imc<-peso/(altura*altura)
 escreva("Nome:", nome ," altura:", altura ,"mts peso:" , peso , "kg")
 escreva ("imc:",imc)
 
 
 
Fimalgoritmo